spring.application.name=customerServices

server.port=8090

spring.main.banner-mode=off


spring.datasource.url=jdbc:mysql://localhost:3306/insurance
spring.datasource.username=springstudent
spring.datasource.password=springstudent


# Show only INFO level logs globally
logging.level.root=INFO

# Suppress Hibernate DEBUG/WARN
logging.level.org.hibernate=ERROR

# Suppress Spring Web DEBUG
logging.level.org.springframework.web=INFO

# Suppress Data JPA warnings
logging.level.org.springframework.data=ERROR

# Suppress HikariCP logs
logging.level.com.zaxxer.hikari=ERROR
